// This type is used to define the shape of our data.
// You can use a Zod schema here if you want.
type Payment = {
  id: string
  amount: number
  status: 'pending' | 'processing' | 'success' | 'failed'
  email: string
  value: number
  age: number
  name: string
  parent: string
  wallet: string
  dropped: boolean
}
export const data: Payment[] = [
  {
    id: '1',
    amount: 245.5,
    status: 'success',
    email: 'john.doe1@example.com',
    value: 10,
    age: 25,
    name: 'John Doe',
    parent: 'Jane Doe',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '2',
    amount: 123.45,
    status: 'pending',
    email: 'mary.jane2@example.com',
    value: 20,
    age: 30,
    name: 'Mary Jane',
    parent: 'John Jane',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '3',
    amount: 360.75,
    status: 'processing',
    email: 'alice.smith3@example.com',
    value: 15,
    age: 22,
    name: 'Alice Smith',
    parent: 'Robert Smith',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '4',
    amount: 89.99,
    status: 'failed',
    email: 'bob.brown4@example.com',
    value: 25,
    age: 27,
    name: 'Bob Brown',
    parent: 'Anna Brown',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '5',
    amount: 560.5,
    status: 'success',
    email: 'carol.jones5@example.com',
    value: 18,
    age: 34,
    name: 'Carol Jones',
    parent: 'Mark Jones',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '6',
    amount: 312.0,
    status: 'processing',
    email: 'dave.wilson6@example.com',
    value: 30,
    age: 40,
    name: 'Dave Wilson',
    parent: 'Nancy Wilson',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '7',
    amount: 180.25,
    status: 'pending',
    email: 'eve.evans7@example.com',
    value: 22,
    age: 29,
    name: 'Eve Evans',
    parent: 'Sam Evans',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '8',
    amount: 140.55,
    status: 'success',
    email: 'frank.miller8@example.com',
    value: 28,
    age: 36,
    name: 'Frank Miller',
    parent: 'Linda Miller',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '9',
    amount: 230.4,
    status: 'failed',
    email: 'grace.wilson9@example.com',
    value: 12,
    age: 23,
    name: 'Grace Wilson',
    parent: 'Oscar Wilson',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '10',
    amount: 99.99,
    status: 'success',
    email: 'harry.potter10@example.com',
    value: 32,
    age: 21,
    name: 'Harry Potter',
    parent: 'Lily Potter',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '11',
    amount: 175.65,
    status: 'pending',
    email: 'ian.thomas11@example.com',
    value: 17,
    age: 28,
    name: 'Ian Thomas',
    parent: 'Sarah Thomas',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '12',
    amount: 315.9,
    status: 'processing',
    email: 'julia.moore12@example.com',
    value: 16,
    age: 39,
    name: 'Julia Moore',
    parent: 'Peter Moore',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '13',
    amount: 205.1,
    status: 'failed',
    email: 'kevin.king13@example.com',
    value: 21,
    age: 42,
    name: 'Kevin King',
    parent: 'Mary King',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '14',
    amount: 129.75,
    status: 'success',
    email: 'lisa.white14@example.com',
    value: 35,
    age: 35,
    name: 'Lisa White',
    parent: 'Daniel White',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '15',
    amount: 270.3,
    status: 'pending',
    email: 'mike.jones15@example.com',
    value: 24,
    age: 26,
    name: 'Mike Jones',
    parent: 'Rebecca Jones',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '16',
    amount: 400.6,
    status: 'processing',
    email: 'nina.robinson16@example.com',
    value: 20,
    age: 33,
    name: 'Nina Robinson',
    parent: 'Greg Robinson',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '17',
    amount: 340.45,
    status: 'failed',
    email: 'oliver.green17@example.com',
    value: 29,
    age: 37,
    name: 'Oliver Green',
    parent: 'Amy Green',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '18',
    amount: 155.8,
    status: 'success',
    email: 'paul.martin18@example.com',
    value: 27,
    age: 31,
    name: 'Paul Martin',
    parent: 'Janet Martin',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '19',
    amount: 215.35,
    status: 'pending',
    email: 'quincy.hall19@example.com',
    value: 14,
    age: 24,
    name: 'Quincy Hall',
    parent: 'Hannah Hall',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '20',
    amount: 185.99,
    status: 'processing',
    email: 'rachel.lee20@example.com',
    value: 26,
    age: 29,
    name: 'Rachel Lee',
    parent: 'Henry Lee',
    wallet: 'digital-wallet',
    dropped: true,
  },

  {
    id: '21',
    amount: 230.25,
    status: 'success',
    email: 'steve.clark21@example.com',
    value: 19,
    age: 38,
    name: 'Steve Clark',
    parent: 'Laura Clark',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '22',
    amount: 175.45,
    status: 'pending',
    email: 'tina.brown22@example.com',
    value: 12,
    age: 27,
    name: 'Tina Brown',
    parent: 'Paul Brown',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '23',
    amount: 305.75,
    status: 'processing',
    email: 'ursula.smith23@example.com',
    value: 14,
    age: 33,
    name: 'Ursula Smith',
    parent: 'Ron Smith',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '24',
    amount: 415.9,
    status: 'failed',
    email: 'victor.harris24@example.com',
    value: 11,
    age: 22,
    name: 'Victor Harris',
    parent: 'Grace Harris',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '25',
    amount: 110.65,
    status: 'success',
    email: 'wendy.lee25@example.com',
    value: 31,
    age: 36,
    name: 'Wendy Lee',
    parent: 'Tom Lee',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '26',
    amount: 125.3,
    status: 'pending',
    email: 'xavier.reed26@example.com',
    value: 27,
    age: 29,
    name: 'Xavier Reed',
    parent: 'Nancy Reed',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '27',
    amount: 295.85,
    status: 'processing',
    email: 'yara.jones27@example.com',
    value: 23,
    age: 41,
    name: 'Yara Jones',
    parent: 'George Jones',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '28',
    amount: 165.4,
    status: 'failed',
    email: 'zachary.moore28@example.com',
    value: 24,
    age: 25,
    name: 'Zachary Moore',
    parent: 'Holly Moore',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '29',
    amount: 350.75,
    status: 'success',
    email: 'alice.baker29@example.com',
    value: 13,
    age: 32,
    name: 'Alice Baker',
    parent: 'Edward Baker',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '30',
    amount: 210.15,
    status: 'pending',
    email: 'brian.gray30@example.com',
    value: 28,
    age: 30,
    name: 'Brian Gray',
    parent: 'Sandra Gray',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '31',
    amount: 275.35,
    status: 'processing',
    email: 'charlotte.green31@example.com',
    value: 16,
    age: 39,
    name: 'Charlotte Green',
    parent: 'Frank Green',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '32',
    amount: 98.45,
    status: 'failed',
    email: 'daniel.hill32@example.com',
    value: 29,
    age: 24,
    name: 'Daniel Hill',
    parent: 'Pamela Hill',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '33',
    amount: 144.6,
    status: 'success',
    email: 'eliza.thomas33@example.com',
    value: 22,
    age: 26,
    name: 'Eliza Thomas',
    parent: 'Ian Thomas',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '34',
    amount: 389.75,
    status: 'pending',
    email: 'frank.ross34@example.com',
    value: 18,
    age: 35,
    name: 'Frank Ross',
    parent: 'Carla Ross',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '35',
    amount: 200.8,
    status: 'processing',
    email: 'george.price35@example.com',
    value: 30,
    age: 42,
    name: 'George Price',
    parent: 'Leah Price',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '36',
    amount: 132.1,
    status: 'failed',
    email: 'hannah.james36@example.com',
    value: 17,
    age: 28,
    name: 'Hannah James',
    parent: 'Chris James',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '37',
    amount: 270.55,
    status: 'success',
    email: 'ian.morgan37@example.com',
    value: 26,
    age: 29,
    name: 'Ian Morgan',
    parent: 'Diane Morgan',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '38',
    amount: 315.9,
    status: 'pending',
    email: 'jane.ward38@example.com',
    value: 21,
    age: 37,
    name: 'Jane Ward',
    parent: 'Robert Ward',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '39',
    amount: 199.75,
    status: 'processing',
    email: 'keith.hall39@example.com',
    value: 19,
    age: 31,
    name: 'Keith Hall',
    parent: 'Nancy Hall',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '40',
    amount: 89.4,
    status: 'failed',
    email: 'linda.king40@example.com',
    value: 32,
    age: 34,
    name: 'Linda King',
    parent: 'Mark King',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '41',
    amount: 140.55,
    status: 'success',
    email: 'matthew.scott41@example.com',
    value: 14,
    age: 38,
    name: 'Matthew Scott',
    parent: 'Helen Scott',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '42',
    amount: 185.3,
    status: 'pending',
    email: 'natalie.adams42@example.com',
    value: 28,
    age: 27,
    name: 'Natalie Adams',
    parent: 'Chris Adams',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '43',
    amount: 205.9,
    status: 'processing',
    email: 'owen.martin43@example.com',
    value: 23,
    age: 33,
    name: 'Owen Martin',
    parent: 'Laura Martin',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '44',
    amount: 175.75,
    status: 'failed',
    email: 'peter.moore44@example.com',
    value: 11,
    age: 24,
    name: 'Peter Moore',
    parent: 'Olivia Moore',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '45',
    amount: 265.35,
    status: 'success',
    email: 'quinn.rogers45@example.com',
    value: 20,
    age: 36,
    name: 'Quinn Rogers',
    parent: 'John Rogers',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '46',
    amount: 280.15,
    status: 'pending',
    email: 'rose.lee46@example.com',
    value: 22,
    age: 29,
    name: 'Rose Lee',
    parent: 'Harry Lee',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '47',
    amount: 310.9,
    status: 'processing',
    email: 'samuel.cox47@example.com',
    value: 15,
    age: 40,
    name: 'Samuel Cox',
    parent: 'Patricia Cox',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '48',
    amount: 99.99,
    status: 'failed',
    email: 'tina.clark48@example.com',
    value: 26,
    age: 32,
    name: 'Tina Clark',
    parent: 'Jason Clark',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '49',
    amount: 140.0,
    status: 'success',
    email: 'ursula.foster49@example.com',
    value: 10,
    age: 34,
    name: 'Ursula Foster',
    parent: 'Jerry Foster',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '50',
    amount: 160.5,
    status: 'pending',
    email: 'victor.morris50@example.com',
    value: 17,
    age: 27,
    name: 'Victor Morris',
    parent: 'Nancy Morris',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '51',
    amount: 375.25,
    status: 'processing',
    email: 'wendy.reed51@example.com',
    value: 25,
    age: 42,
    name: 'Wendy Reed',
    parent: 'George Reed',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '52',
    amount: 290.45,
    status: 'failed',
    email: 'xander.bell52@example.com',
    value: 13,
    age: 38,
    name: 'Xander Bell',
    parent: 'Linda Bell',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '53',
    amount: 199.99,
    status: 'success',
    email: 'yolanda.stone53@example.com',
    value: 31,
    age: 23,
    name: 'Yolanda Stone',
    parent: 'Samuel Stone',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '54',
    amount: 119.75,
    status: 'pending',
    email: 'zachary.cole54@example.com',
    value: 18,
    age: 26,
    name: 'Zachary Cole',
    parent: 'Rachel Cole',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '55',
    amount: 289.3,
    status: 'processing',
    email: 'alicia.ward55@example.com',
    value: 29,
    age: 41,
    name: 'Alicia Ward',
    parent: 'Frank Ward',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '56',
    amount: 152.4,
    status: 'failed',
    email: 'bradley.hill56@example.com',
    value: 20,
    age: 25,
    name: 'Bradley Hill',
    parent: 'Jessica Hill',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '57',
    amount: 178.85,
    status: 'success',
    email: 'carla.james57@example.com',
    value: 16,
    age: 39,
    name: 'Carla James',
    parent: 'Paul James',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '58',
    amount: 250.7,
    status: 'pending',
    email: 'dennis.moore58@example.com',
    value: 30,
    age: 24,
    name: 'Dennis Moore',
    parent: 'Patricia Moore',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '59',
    amount: 193.5,
    status: 'processing',
    email: 'emma.lee59@example.com',
    value: 19,
    age: 37,
    name: 'Emma Lee',
    parent: 'Mark Lee',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '60',
    amount: 220.25,
    status: 'failed',
    email: 'frank.harris60@example.com',
    value: 15,
    age: 31,
    name: 'Frank Harris',
    parent: 'Susan Harris',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '61',
    amount: 155.65,
    status: 'success',
    email: 'gina.baker61@example.com',
    value: 13,
    age: 35,
    name: 'Gina Baker',
    parent: 'Robert Baker',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '62',
    amount: 295.1,
    status: 'pending',
    email: 'harry.king62@example.com',
    value: 11,
    age: 29,
    name: 'Harry King',
    parent: 'Nancy King',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '63',
    amount: 165.75,
    status: 'processing',
    email: 'irene.morris63@example.com',
    value: 25,
    age: 28,
    name: 'Irene Morris',
    parent: 'George Morris',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '64',
    amount: 120.3,
    status: 'failed',
    email: 'jason.scott64@example.com',
    value: 14,
    age: 33,
    name: 'Jason Scott',
    parent: 'Linda Scott',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '65',
    amount: 289.4,
    status: 'success',
    email: 'kate.reed65@example.com',
    value: 29,
    age: 39,
    name: 'Kate Reed',
    parent: 'Steve Reed',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '66',
    amount: 132.85,
    status: 'pending',
    email: 'lucas.moore66@example.com',
    value: 27,
    age: 22,
    name: 'Lucas Moore',
    parent: 'Holly Moore',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '67',
    amount: 178.45,
    status: 'processing',
    email: 'mike.stone67@example.com',
    value: 24,
    age: 34,
    name: 'Mike Stone',
    parent: 'Sarah Stone',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '68',
    amount: 150.5,
    status: 'failed',
    email: 'nora.brown68@example.com',
    value: 22,
    age: 26,
    name: 'Nora Brown',
    parent: 'Paul Brown',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '69',
    amount: 220.75,
    status: 'success',
    email: 'oliver.james69@example.com',
    value: 18,
    age: 40,
    name: 'Oliver James',
    parent: 'Anna James',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '70',
    amount: 365.55,
    status: 'pending',
    email: 'paula.green70@example.com',
    value: 30,
    age: 27,
    name: 'Paula Green',
    parent: 'Frank Green',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '71',
    amount: 199.95,
    status: 'processing',
    email: 'quincy.hall71@example.com',
    value: 16,
    age: 36,
    name: 'Quincy Hall',
    parent: 'Laura Hall',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '72',
    amount: 99.85,
    status: 'failed',
    email: 'rachel.lee72@example.com',
    value: 17,
    age: 32,
    name: 'Rachel Lee',
    parent: 'Henry Lee',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '73',
    amount: 249.75,
    status: 'success',
    email: 'steve.clark73@example.com',
    value: 13,
    age: 31,
    name: 'Steve Clark',
    parent: 'Nancy Clark',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '74',
    amount: 120.35,
    status: 'pending',
    email: 'tina.wilson74@example.com',
    value: 24,
    age: 29,
    name: 'Tina Wilson',
    parent: 'Tom Wilson',
    wallet: 'bank-account',
    dropped: false,
  },
  {
    id: '75',
    amount: 190.5,
    status: 'processing',
    email: 'victor.adams75@example.com',
    value: 15,
    age: 34,
    name: 'Victor Adams',
    parent: 'Grace Adams',
    wallet: 'e-wallet',
    dropped: true,
  },
  {
    id: '76',
    amount: 165.25,
    status: 'failed',
    email: 'wendy.hall76@example.com',
    value: 31,
    age: 26,
    name: 'Wendy Hall',
    parent: 'Sam Hall',
    wallet: 'digital-wallet',
    dropped: false,
  },
  {
    id: '77',
    amount: 299.55,
    status: 'success',
    email: 'xavier.jones77@example.com',
    value: 14,
    age: 38,
    name: 'Xavier Jones',
    parent: 'Karen Jones',
    wallet: 'bank-account',
    dropped: true,
  },
  {
    id: '78',
    amount: 145.9,
    status: 'pending',
    email: 'yara.morgan78@example.com',
    value: 20,
    age: 28,
    name: 'Yara Morgan',
    parent: 'Robert Morgan',
    wallet: 'e-wallet',
    dropped: false,
  },
  {
    id: '79',
    amount: 275.65,
    status: 'processing',
    email: 'zachary.ross79@example.com',
    value: 27,
    age: 29,
    name: 'Zachary Ross',
    parent: 'Helen Ross',
    wallet: 'digital-wallet',
    dropped: true,
  },
  {
    id: '80',
    amount: 150.5,
    status: 'failed',
    email: 'alice.wilson80@example.com',
    value: 19,
    age: 32,
    name: 'Alice Wilson',
    parent: 'George Wilson',
    wallet: 'bank-account',
    dropped: false,
  },
]
